### ISSUE TITLE
Export vendored-openssl feature for git2

### ISSUE THREAD

**Issue by bnjjj** [de-vri-es/auth-git2-rs#1]
When you introduced this crate [here](https://github.com/iomentum/cargo-scaffold/pull/40) it creates a dependency to `git2` without the openssl vendored. That's an issue for us, could you re export the `vendored-openssl` of git2 to benefit from that feature please ?

Thanks a lot

**Comment by de-vri-es** [comment]
Hey! I don't mind adding them, but doesn't feature unification solve the problem already when you also depend directly on `git2`?

See https://doc.rust-lang.org/cargo/reference/features.html#feature-unification for more information.

**Comment by de-vri-es** [comment]
Hmm, the more I think about it, because we're not publically re-exporting `git2`, the more I think this should not be needed. Do you have an example where this is causing problems?

**Comment by bnjjj** [comment]
You're right @de-vri-es ! My bad, our cargo deny was suddenly rejecting the cargo-scaffold upgrade because it thought it introduces openssl. After comparing both `cargo tree` they were the same. The issue was located in our `deny.toml` file with a specific exception we wrote. I'm sorry for the noise. This issue can be closed :) thanks !

**Comment by de-vri-es** [comment]
No problem! Glad that it's working properly! :D
